# Generated by Django 6.0.4 on 2026-05-29 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='status',
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время окончания отправки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время первой отправки'),
            preserve_default=False,
        ),
    ]
